### ISSUE TITLE
How do the instances synchronise changes to flows, ...?

### ISSUE THREAD

**Issue by andreaswittig** [guysqr/node-red-ha-on-aws#2]
Your approach looks promising. However, I'm wondering how state gets synchronized between the instances. For example, what happens when a user saves a new version of a flow. How does the other EC2 instance notice that change to make sure it fetches the data again from EFS?

**Comment by guysqr** [comment]
There’s a watcher on the file system that triggers the reload. Does that answer your question?

Regards

Guy

On 12 Nov 2019, at 8:09 pm, Andreas Wittig <notifications@github.com> wrote:

﻿

Your approach looks promising. However, I'm wondering how state gets synchronized between the instances. For example, what happens when a user saves a new version of a flow. How does the other EC2 instance notice that change to make sure it fetches the data again from EFS?

**Comment by andreaswittig** [comment]
Thanks a lot for your help, @guysqr. Could you please point me to the code which triggers the reload?

**Comment by guysqr** [comment]
Have a look in the package.json, the start command configures node red to run under nodemon with the appropriate watcher. 

Regards

Guy

On 12 Nov 2019, at 9:18 pm, Andreas Wittig <notifications@github.com> wrote:

﻿

Thanks a lot for your help, @guysqr. Could you please point me to the code which triggers the reload?

**Comment by andreaswittig** [comment]
Thanks a lot @guysqr.
